[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "browserforge>=1.2.4",
    "camoufox>=0.4.11",
    "curl-cffi>=0.14.0",
    "lxml>=6.0.2",
    "msgspec>=0.20.0",
    "patchright>=1.58.0",
    "pdfminer-six>=20260107",
    "playwright>=1.57.0",
    "pymupdf>=1.27.2.3",
    "python-docx>=1.2.0",
    "rebrowser-playwright>=1.52.0",
    "requests>=2.32.5",
    "scrapling>=0.4.1",
]
